### ISSUE TITLE
not able to install with NPM

### ISSUE THREAD

**Issue by Lilly3252** [DevSnowflake/quick.eco-mongo#1]
when i try to install the manager for mongoDB i got that error :

Au caractère Ligne:1 : 7
+ npm i @quick.eco/mongo
+       ~~~~~~

Cannot use the "@" projection operator to reference variables in an expression. "@Quick" can only be used as an argument to a command. To reference variables in an expression, use "$ quick".

so i tried npm i $quick.eco/mongo And i got this error :
npm ERR! Could not install from "..\..\..\..\..\mongo" as it does not contain a package.json file.

i have "mongoose": "^5.10.13" and "quick.eco": "^6.0.0", installed. i would like to know if it's a bug or something else. thank you very much.

**Comment by twlite** [comment]
maybe you are on `powershell` 

Try `npm i "@quick.eco/mongo"`

**Comment by Lilly3252** [comment]
![image](https://user-images.githubusercontent.com/74218901/101523040-0e9be300-3956-11eb-801c-183611617b05.png)
i tried this on powershell inside Visual Studio Code

**Comment by twlite** [comment]
you can either:
- Enter `cmd` by writing `cmd`
- Run `npm i @quick.eco/mongo`

Or:
- Run `npm i "@quick.eco/mongo"`

**Comment by Lilly3252** [comment]
Oh wow ! , i didn't know those " " would solved the problem actually haha. i'm so sorry for this ! 
![image](https://user-images.githubusercontent.com/74218901/101563485-4d9e5880-3997-11eb-9e96-fefd5970d991.png)
it did work , i thank you so much :) !
